### ISSUE TITLE
InputAutocomplete 내장 API

### ISSUE THREAD

**Issue by MONOTYPEEE** [Team-Submit/23-EMB-FE#33]
InputAuto 컴포넌트에 API 통신을 내장하는 방향이 물론 한번만 사용되는 컴포넌트긴 하지만 그래도 common 디렉토리에 들어 있는데 좋은 방향은 아닌것 같습니다

**Comment by applely25** [comment]
그러면 따로 빼서 타입을 부서로 받았을때 api 연동되는 방향으로 수정해볼까요?

**Comment by applely25** [comment]
그러면 부서 input인지 아닌지 prop으로 받아와서 부서 inputAuto이면 연동을 하는 로직으로 하면 괜찮을까요?

**Comment by MONOTYPEEE** [comment]
그렇게 복잡하게 하는것보단 원본 컴포넌트에 최대한 손 안 대는 방향으로
Wrapper처럼 컴포넌트를 더 만드는 방향이 좋을 것 같습니다

**Comment by applely25** [comment]
아 부서전용 InputAuto 컴포넌트를 하나 만들으라는 말씀인가요?

**Comment by applely25** [comment]
근데 지금 생각해보니까 지금 이름 바꿔서 input 새로 만들면 개발하는데 고칠게 많지 않을까요? 그냥 prop으로 타입하나 만드는게 더 좋을 것 같은데 어떻게 생각하세요....?흠...

**Comment by MONOTYPEEE** [comment]
새로 개발하는건 아니고 list 돌려놓고
```js
func DepartmentAutocomplete(){
    const data = getDepartment()
    return(
        <InputAuto list={data}/>
```

이런느낌으로 Wrapper

**Comment by applely25** [comment]
그게 아니라 이미 InputAuto 컴포넌트를 불러와서 사용중인 사람들은 import를 새로운 이름으로 다시 해야한다는 문제가 있다는 뜻임.
에러 고치는거 그냥 알아서 하라고하고 수정할가?
